config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :controllers => {
      :registrations => 'registrations',
      :omniauth_callbacks => 'omniauth_callbacks'
    }

  root 'debts#index', :owner => 'my'


  resources :contacts

  post '/add_contact' => 'contacts#create', :as => :add_contact

  # get 'debts/:owner' => 'debts#show'

  # get 'debts/new' => 'debts#new'

# post '/debts' => 'debts#create', :as => :add_debt

  resources :debts, :only => [:new, :create, :edit, :update, :destroy]

  get 'debts/:owner' => 'debts#index'


  get 'contacts/send_invite/:email', :to => 'contacts#invite',
    :as => 'send_invite', :format => false, :constraints => {:email => /[^\/]+/}

end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  contact_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Contact < ActiveRecord::Base

  belongs_to :user
  belongs_to :contact, :class_name => 'User'

end

app/models/debt.rb
# == Schema Information
#
# Table name: debts
#
#  id         :integer          not null, primary key
#  amount     :decimal(, )
#  comment    :text
#  owner_id   :integer
#  payer_id   :integer
#  start_date :date
#  due_date   :date
#  paid_date  :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  paid       :boolean          default(FALSE)
#

class Debt < ActiveRecord::Base

  belongs_to :owner, :class_name => 'User', :foreign_key => 'owner_id'
  belongs_to :payer, :class_name => 'User', :foreign_key => 'payer_id'


  scope :unpaid, -> { where(:paid => false) }

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  full_name              :string
#  contact_number         :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :contacts
  has_many :contact, :through => :contacts

  has_many :inverse_contacts, :class_name => 'Contact', :foreign_key => 'contact_id'
  has_many :inverse_friends, :through => :inverse_contacts, :source => :user

  has_many :debts, :foreign_key => 'owner_id'
  has_many :inverse_debts, :class_name => 'Debt', :foreign_key => 'payer_id'


  devise :omniauthable, :omniauth_providers => [:google_oauth2]


  def self.from_omniauth access_token
    data = access_token.info

    User.where(:email => data['email']).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!


  layout :choose_layout





  protected

  def choose_layout
    return 'session' unless signed_in?
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_filter :initialize_contact_id, :only => [:create]


  def index
    @contacts = current_user.contacts.all
  end


  def create
  if self.contact_exists?
      flash[:alert] = "Already a contact!"
      return redirect_to :contacts
    end

    @contact = current_user.contacts.build(:contact_id => @contact_id)

    @contact.save ?
      flash[:notice] = "Added contact." :
      flash[:error] = "Unable to add contact."

    redirect_to :contacts
  end


  def destroy
    @contact = current_user.contacts.find(params[:id])
    @contact.destroy
    flash[:notice] = "Removed contact."
    redirect_to current_user
  end


  def invite
    OwerightMailer.send_contact_invitation(params[:email], current_user).deliver_now

    redirect_to :contacts, :notice => "Successfully sent an invitation to #{params[:email]}."
  end




  protected

  def initialize_contact_id
    user = User.where(:email => params[:contact_email]).first

    if user.nil?
      flash[:alert] = "User doesn't Exist!"
      return redirect_to contacts_path(:email => params[:contact_email])
    else
      @contact_id = user.id
    end
  end


  def contact_exists?
    current_user.contacts.where(:contact_id => @contact_id).any?
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  end

end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController

  before_filter :initialize_debt, :only => [:edit, :update, :destroy]

  def index
    @debts =
      (params[:owner] == 'theirs') ?
        current_user.debts :
        current_user.inverse_debts
  end


  def new
    @debt = Debt.new
  end


  def edit
  end


  def update
    @debt.update_attributes(debt_params) ?
      flash[:notice] = 'Successfully updated debt.' :
      flash[:notice] = 'Failed to update debt.'

    redirect_to :back
  end


  def create
    attributes = debt_params.clone

    unless self.params_valid? attributes
      flash[:error] = 'Unable to Create Debt. Please fillup required fields.'
      return redirect_to(:back)
    end

    self.check_owner attributes

    @debt = Debt.new attributes


    if @debt.save
      flash[:notice] = 'Debt Created.'


      OwerightMailer.notify_payer(@debt).deliver_now unless @debt.paid
    else
      flash[:error] = 'Unable to Create Debt.'
    end

    redirect_to :back
  end


  def destroy
    @debt.destroy ?
      flash[:notice] = 'Debt Deleted.' :
      flash[:notice] = 'Unable to Delete Debt.'

    redirect_to :back
  end




  protected

  def initialize_debt
    @debt = Debt.find params[:id]
  end


  def params_valid? attributes
    attributes[:owner_id].present? || attributes[:payer_id].present?
  end


  def check_owner attributes
    if  attributes[:owner_id].blank?
      attributes[:owner_id] = current_user.id
    elsif attributes[:payer_id].blank?
      attributes[:payer_id] = current_user.id
    end

    attributes
  end







  private

  def debt_params
    params.require(:debt).permit(:amount, :comment, :owner_id, :payer_id,
      :start_date, :due_date, :paid_date, :paid)
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController


  def google_oauth2
      @user = User.from_omniauth request.env['omniauth.auth']

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', :kind => 'Google'
        sign_in_and_redirect @user, :event => :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController





  private

  def sign_up_params
    params.require(:user).permit :full_name, :email, :contact_number, :password, :password_confirmation
  end

  def account_update_params
    params.require(:user).permit :full_name, :email, :contact_number, :password, :password_confirmation, :current_password
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.haml
- if params[:email].present?
  .alert.alert-dismissible{:role => "alert", :class => "alert-info"}
    %button.close{'aria-label' => 'Close', 'data-dismiss' => 'alert', :type => 'button'}
      %span{"aria-hidden" => "true"} ×
    Invite #{params[:email]} to use OWERIGHT.
    %span
      = link_to 'Send Invitation', send_invite_path(:email => params[:email]), :class => 'btn btn-sm btn-success'


%h1
  Contacts
  %span
    %a.btn.btn-success{'aria-controls' => 'contact-form', 'aria-expanded' => 'false', 'data-toggle' => 'collapse', :href => '#contact-form', :role => 'button'}
      Add contact



#contact-form.collapse
  .well
    = form_tag :add_contact do
      = email_field_tag :contact_email, nil, :placeholder => 'Email Address'
      = submit_tag 'ADD'

.padding-top

%table.table
  %tr
    %th Full Name
    %th Email
    %th Contact Number

  - @contacts.each do |contact|
    %tr
      %td= contact.contact.full_name
      %td= contact.contact.email
      %td= contact.contact.contact_number






- if current_user.inverse_friends.present?
  %h3 People who added me:
  %ul
    - for user in current_user.inverse_friends
      %li=h user.email

app/views/dashboard/index.haml
%h1 Dashboard#index

= current_user.email
%br
= current_user.full_name
%br
= current_user.contact_number

app/views/debts/_form.haml
-#
-# locals:
-#    debt
-#


= form_for @debt do |f|
  - if debt.errors.any?
    #error_explanation
      %h2
        = pluralize(debt.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - debt.errors.full_messages.each do |msg|
          %li= msg

  - if @debt.new_record?
    .form-group
      = f.label :owner, 'Their Debt'
      %input#js-debt-owner{:type => 'checkbox', :name => 'debt-owner', :value => 'true'}

  .form-group
    = f.label :paid
    = f.check_box :paid, {:id => 'js-debt-paid'}, true

  .form-group
    = f.label :amount
    = f.text_field :amount, :autofocus => true, :required => true

  .form-group
    = f.label :comment
    = f.text_area :comment

  - if @debt.new_record?
    .form-group.js-owner-id
      = f.label :owner_id

      .input-group
        = f.collection_select(:owner_id, current_user.contacts.map { |contact| contact.contact }, :id, :full_name, :prompt => 'Select contact whom you owe')
        %span.input-group-btn
          = link_to [:contacts], :class => 'btn btn-primary' do
            %span.glyphicon.glyphicon-plus{'aria-hidden' => true}


    .form-group.js-payer-id
      = f.label :payer_id
      = f.collection_select(:payer_id, current_user.contacts.map { |contact| contact.contact }, :id, :full_name, :prompt => 'Select contact who owe you')

    .form-group
      = f.label :start_date, 'Created at'
      = f.date_select :start_date

  .form-group.js-paid-date
    = f.label :paid_date
    = f.date_select :paid_date

  = f.submit 'Submit', :class => 'btn btn-success'

app/views/debts/edit.haml
.col-md-6
  %h1 Edit Debt

  = render :partial => 'form', :locals => {:debt => @debt}

app/views/debts/index.haml
- owner = params[:owner] == 'my' ? 'My' : 'Their'

%h1
  #{owner} Debts
  %span
    = link_to 'Create Debt', [:new, :debt], :class => 'btn btn-success'

.padding-top

%h3 Unpaid Total: #{number_to_currency @debts.unpaid.map.sum(&:amount), :locale => :ph}

%table.table
  %tr
    %th #{params[:owner] == 'my' ? 'To' : 'From'}
    %th Amount
    %th Comment
    %th Created At
    %th Paid
    - if params[:owner] == 'theirs'
      %th
      %th
    - else
      %th

  - @debts.each do |debt|
    %tr
      %td= "#{params[:owner] == 'my' ? debt.owner.full_name : debt.payer.full_name}"
      %td= number_to_currency debt.amount, :locale => :ph
      %td= debt.comment
      %td= debt.start_date.strftime '%b-%d-%Y'
      %td= debt.paid ? 'Yes' : 'No'
      - if params[:owner] == 'theirs'
        %td
          = link_to [:edit, debt], :class => 'btn btn-sm btn-success form-control' do
            %span.glyphicon.glyphicon-edit{'aria-hidden' => true}
        %td
          = link_to [debt], :class => 'btn btn-sm btn-danger form-control',
            :method => :delete do
            %span.glyphicon.glyphicon-trash{'aria-hidden' => true}
      - else
        %td
          = link_to 'Send Email', '#', :class => 'btn btn-sm btn-success'

app/views/debts/new.haml
.col-md-6
  %h1 New Debt

  = render :partial => 'form', :locals => {:debt => @debt}

app/views/debts/show.haml
%h1 Debts

app/views/layouts/application.haml
!!!
%html
  %head
    %title Oweright
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .page-container
      / top navbar
      %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
        .navbar-header
          %button.navbar-toggle{"data-target" => ".sidebar-nav", "data-toggle" => "offcanvas", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'OWERIGHT', '/', :class => 'navbar-brand'


      .container-fluid
        .row.row-offcanvas.row-offcanvas-left
          = render :partial => 'shared/sidebar'
          / /main
          .col-xs-12.col-sm-9{"data-spy" => "scroll", "data-target" => "#sidebar-nav"}

            - flash.each do |type, msg|
              - type = type == 'alert' ? 'danger' : 'info'


              .alert.alert-dismissible{:role => "alert", :class => "alert-#{type}"}
                %button.close{'aria-label' => 'Close', 'data-dismiss' => 'alert', :type => 'button'}
                  %span{"aria-hidden" => "true"} ×
                = msg

            = yield

    = render :partial => 'shared/footer'

app/views/layouts/session.haml
!!!
%html
  %head
    %title Oweright
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .page-container
      / top navbar
      %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
        .navbar-header
          = link_to 'OWERIGHT', '#', :class => 'navbar-brand'

      .container-fluid.padding-top
        .row
          .col-md-4.col-md-offset-4
            = yield

    = render :partial => 'shared/footer'

app/views/shared/_footer.haml
%footer
  .container
    .row
      .col-sm-6 penakanoobs@2015

app/views/shared/_sidebar.haml
#sidebar.col-xs-6.col-sm-3.sidebar-offcanvas{:role => 'navigation'}
  %div{'data-offset-bottom' => '90', 'data-offset-top' => '45', 'data-spy' => 'affix'}
    %ul#sidebar-nav.nav
      %li
        = link_to '/debts/my' do
          %span.glyphicon.glyphicon-user{'aria-hidden' => true}
          My Debts
      %li
        = link_to '/debts/theirs' do
          %span.glyphicon.glyphicon-chevron-right{'aria-hidden' => true}
          Their Debts

      - if user_signed_in?
        %li
          = link_to [:contacts] do
            %span.glyphicon.glyphicon-book{'aria-hidden' => true}
            Contacts
        %li
          = link_to destroy_user_session_path, :method => :delete do
            %span.glyphicon.glyphicon-off{'aria-hidden' => true}
            Logout, #{current_user.email}